// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUquxnpZIfVuLkF722gCmpd-6_k6NRT5k',
    appId: '1:1013914441659:web:87c3e6c7fed4bca818569e',
    messagingSenderId: '1013914441659',
    projectId: 'lectio-divina-ef223',
    authDomain: 'lectio-divina-ef223.firebaseapp.com',
    storageBucket: 'lectio-divina-ef223.firebasestorage.app',
    measurementId: 'G-K59FWWMXHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LUGUCvLhuKBCYqMHFg5xqCsZs2UH-Js',
    appId: '1:1013914441659:android:c3a4610abee5ae0818569e',
    messagingSenderId: '1013914441659',
    projectId: 'lectio-divina-ef223',
    storageBucket: 'lectio-divina-ef223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqnpsD_IxKPsM9-GVn70FrvgeOrTlCvs',
    appId: '1:1013914441659:ios:fab797e0d3803cd618569e',
    messagingSenderId: '1013914441659',
    projectId: 'lectio-divina-ef223',
    storageBucket: 'lectio-divina-ef223.firebasestorage.app',
    iosBundleId: 'sk.dpapp.app.ios604688a889d93',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqnpsD_IxKPsM9-GVn70FrvgeOrTlCvs',
    appId: '1:1013914441659:ios:fab797e0d3803cd618569e',
    messagingSenderId: '1013914441659',
    projectId: 'lectio-divina-ef223',
    storageBucket: 'lectio-divina-ef223.firebasestorage.app',
    iosBundleId: 'sk.dpapp.app.ios604688a889d93',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUquxnpZIfVuLkF722gCmpd-6_k6NRT5k',
    appId: '1:1013914441659:web:255925b024ba1e6a18569e',
    messagingSenderId: '1013914441659',
    projectId: 'lectio-divina-ef223',
    authDomain: 'lectio-divina-ef223.firebaseapp.com',
    storageBucket: 'lectio-divina-ef223.firebasestorage.app',
    measurementId: 'G-6DTH3EJ8PH',
  );
}
